baseURL = "https://edmontongo.org/"
copyright = "Edmonton Go"
locale = "en"
title = "Edmonton Go"

DefaultContentLanguage = "en"
theme = "clarity"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 4

[deployment]
[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"

[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
pattern = "^.+\\.(png|jpg|gif|webp)$"

[[deployment.matchers]]
contentType = "application/xml"
gzip = true
pattern = "^sitemap\\.xml$"

[[deployment.matchers]]
gzip = true
pattern = "^.+\\.(html|xml|json)$"

# hugo.toml example
[[headers]]
for = "/**"
[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' edmontongo.org;"
# Add other security headers here
Feature-Policy = "vibrate 'none'; geolocation 'none'"
Permissions-Policy = "geolocation=(), microphone=()"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
