baseURL = 'https://edmontongo.org/'
languageCode = 'en-us'
title = 'Edmonton Go'
theme = 'edmontongo'
Paginate = 3

[params]
author = "Peter Preeper"
description = "Edmonton Go Meetup"

[permalinks]
year = "/meetup/:slug/"
tag = "/tags/:slug/"

[taxonomies]
year = "year"
tag = "tags"

[deployment]
[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
