baseURL = 'https://edmontongo.org/'
languageCode = 'en-us'
title = 'Edmonton Go'
theme = 'edmontongo'
Paginate = 3

[params]
author = "Peter Preeper"
description = "Edmonton Go Meetup"

[permalinks]
year = "/meetup/:slug/"
tag = "/tags/:slug/"

[taxonomies]
year = "year"
tag = "tags"
