baseurl = "https://edmontongo.org/"
languageCode = "en-us"
title = "Edmonton Go"

[permalinks]
post = "/:filename/"
workshop = "/:filename/"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
URL = "s3://edmontongo.org?region=ca-central-1"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
