# menus
[[main]]
name = "Meetups"
url = "/meetup/"
weight = 1

[[main]]
name = "Presentations"
url = "/presentations/"
weight = 2

[[main]]
name = "Blog"
url = "/blog/"
weight = 3

[[main]]
name = "Program"
url = "/program/"
weight = 4

[[main]]
name = "Get Involved"
url = "/get-involved/"
weight = 5

[[main]]
name = "About Us"
url = "/about/"
weight = 6

# social menu links

[[social]]
name = "github"
type = "social"
weight = 1
url = "https://github.com/edmontongo"

[[social]]
name = "rss"
weight = 4
url = "index.xml"
